# Generated by Django 5.1.3 on 2025-01-03 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_paciente_historial_de_citas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='alergias',
            new_name='allergies',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_nacimiento',
            new_name='birthDate',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='horarios_disponibles',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medico_tratante',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombre_emergencia',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono_emergencia',
        ),
        migrations.AddField(
            model_name='medico',
            name='apellido_medico',
            field=models.CharField(default='Apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='medico',
            name='horario_disponible',
            field=models.CharField(default='Lunes a Viernes de 8:00 a 18:00', max_length=50),
        ),
        migrations.AddField(
            model_name='medico',
            name='horario_no_disponible',
            field=models.CharField(default='Sábados y Domingos', max_length=50),
        ),
        migrations.AddField(
            model_name='medico',
            name='nombre_medico',
            field=models.CharField(default='Nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='currentMedication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='disclosureConsent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(default='Email', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='emergencyContactName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='emergencyContactNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='familyMedicalHistory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='identificationDocumentId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='identificationDocumentUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='identificationNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='identificationType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='insurancePolicyNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='insuranceProvider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pastMedicalHistory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='phone',
            field=models.CharField(default='Phone', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='primaryPhysician',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='privacyConsent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='treatmentConsent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='userId',
            field=models.CharField(default='User ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='medico',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL),
        ),
    ]
