# Generated by Django 5.1.3 on 2025-01-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_alergias_paciente_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='horario_disponible',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='horario_no_disponible',
            field=models.DateTimeField(),
        ),
    ]
