# Generated by Django 5.1.3 on 2025-01-03 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_medico_horario_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='primaryPhysician',
        ),
        migrations.AddField(
            model_name='paciente',
            name='medico_tratante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_tratados', to='usuarios.medico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='usuarios.usuario'),
        ),
    ]
