# Generated by Django 5.1.3 on 2025-01-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_paciente_primaryphysician_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='allergies',
            new_name='alergias',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='privacyConsent',
            new_name='consentimientoPrivacidad',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='treatmentConsent',
            new_name='consentimiento_tratamiento',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='birthDate',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='gender',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='currentMedication',
            new_name='historial_medico_familiar',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='familyMedicalHistory',
            new_name='historial_pasado_medico',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='pastMedicalHistory',
            new_name='medicacion',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='emergencyContactName',
            new_name='nombre_emergencia',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='identificationNumber',
            new_name='numero_cedula',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='identificationType',
            new_name='numero_de_seguro',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='emergencyContactNumber',
            new_name='numero_emergencia',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='insurancePolicyNumber',
            new_name='ocupacion',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='insuranceProvider',
            new_name='proveedor_seguro',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='phone',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='occupation',
            new_name='tipo_identificacion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='userId',
        ),
        migrations.AlterField(
            model_name='medico',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='usuarios.usuario'),
        ),
    ]
