# Generated by Django 5.1.3 on 2025-01-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_paciente_user_alter_medico_user_and_more'),
        ('usuarios', '0006_rename_allergies_paciente_alergias_and_more'),
    ]

    operations = [
    ]
